### ISSUE TITLE
Fermilevel is not set to zero in bandsplot

### ISSUE THREAD

**Issue by jeev4303** [SMTG-UCL/sumo#119]
Dear developers,
i have plotted the orbital band structure for my system, i found that the fermienergy is not set to zero when plotting. 

the following tag is present in dosplot and not in the bandsplot, could anyone clarify this issue

 --no-shift            don't shift the VBM/Fermi level to 0 eV

thanks in advance,
kind regards
Rajeev

**Comment by utf** [comment]
Can you show the plot you are referring to?

Sumo will only set the Fermi level to zero if the system is metallic. If the system has a band gap, the energies will be zeroed to the valence band maximum (energy of the highest occupied state). The Fermi level given by VASP for insulators/semiconductors has no physical basis and is generally only set half way between the band edges.

**Comment by jeev4303** [comment]
Dear developers,

can i also shift the Fermi level while plotting using sumo. also i have attached the files below link in drive. like to know if any further files required 

https://drive.google.com/drive/folders/1yzSznhbpKMX366nTUKQdC-yV5sGx0Skd?usp=sharing

thanks

**Comment by ajjackson** [comment]
Hi @jeev4303 ,

there have been a couple of developments on this.

Firstly, a bug was fixed in #156 so `--no-shift` should now work correctly in dosplot.

Secondly, #68 adds the ability to override the default energy reference (VBM or EFermi) with a user value, using `--zero-energy`. To draw a line at zero, add `--zero-line`.
