### ISSUE TITLE
Correct Band Gap in sumo-bandstats?

### ISSUE THREAD

**Issue by jfrmhrz** [SMTG-UCL/sumo#191]
I have done a non-spin polarized band structure calculation of a TMD material, by checking the band gap type and value using sumo-bandstats, there seems to be Indirect and Direct band gap as follows: 
    2   |   Indirect band gap: 0.924 eV
   3   │  Direct band gap: 0.989 eV
   4   │   k-point: [0.28, 0.00, 0.00]
   5   │   k-point indices: 26
   6   │   Band indices: 152, 153
   7   │
   8   │ Valence band maximum:
   9   │   Energy: -2.089 eV
  10   │   k-point: [-0.00, -0.29, 0.00]
  11   │   k-point location: between X-Y
  12   │   k-point indices: 7
  13   │   Band indices: 152
  14   │
  15   │ Conduction band minimum:
  16   │   Energy: -1.165 eV
  17   │   k-point: [-0.36, -0.00, 0.36]
  18   │   k-point location: between L-Z
  19   │   k-point indices: 64
  20   │   Band indices: 153

I would like to know what is the meaning of this direct band gap here? as I am expecting my material to be an Indirect band gap semiconductor according to the difference between VBM and CBM. 

Could you please explain that @ajjackson 
Thank You.

**Comment by jfrmhrz** [comment]
Thank you very much for your explanation, this material is monolayer ReSe2, which is been reported to have this conflicts of being direct/indirect band gap semiconducting material. Could you please suggest what possible optic calculations to follow in order to confirm the nature of the band structure? 
Thanks

**Comment by ajjackson** [comment]
The first step is simple enough: you can use an `LOPTICS=.TRUE.` calculation with [sumo-optplot](https://smtg-ucl.github.io/sumo/sumo-optplot.html) to have a look at the predicted absorption spectrum. Make sure to use plenty of k-points; you can use the same self-consistency tricks as a band structure calculation. But this plot will probably not be enough to distinguish which transitions are leading to more absorption, when the difference is so small.

To get a better look at the optical transition matrix it is possible to uncomment a line of VASP source and recompile in order to have it write out a plain-text "WAVEDERF" file when calculating optics. This can be inspected to determine which transitions are relevant; sometimes the calculated bandgap is really "dipole-forbidden" and the optical gap is driven by other states. (E.g. see Fig 2 of https://pubs.acs.org/doi/10.1021/acsenergylett.2c01961)

I'm afraid I don't have any handy tools for working with WAVEDERF files and haven't looked at one for a while. Maybe if you ask around you can find someone who will help with that analysis!

I would be very wary of e.g. Tauc plot analysis for this system making a strong assumption that the gap is purely direct or indirect. Until you've looked at the transition matrix it seems safest to assume both are present.

**Comment by JaafarMehrez** [comment]
Thank you very much, that was very informative.
Happy Computing :)

Jaafar Mehrez

**Comment by ajjackson** [comment]
Indeed, good luck with the research!
