### ISSUE TITLE
Add phonopy to the requirements.txt file

### ISSUE THREAD

**Issue by Assassinkin** [SMTG-UCL/sumo#20]

**Comment by ajjackson** [comment]
This was intentional as Phonopy was breaking the ReadTheDocs build due to some unusual design decisions. Thank you for pointing out this potential confusion;I have renamed the requirements file and added a comment to make it clear that it is only intended for use with ReadTheDocs.

Regular users are encouraged to install with Pip/setup.py as all the dependencies are in PyPI. Is there a particular reason you wanted to use requirements.txt?

**Comment by Assassinkin** [comment]
@ajjackson Thanks for that. I m installing it using `python setup.py`. And it was asking for phonopy.
