### ISSUE TITLE
The correct method of passing `Positional Arguments` to this tool.

### ISSUE THREAD

**Issue by hongyi-zhao** [SMTG-UCL/sumo#222]
Based on the document [here](https://smtg-ucl.github.io/sumo/sumo-optplot.html#positional-arguments), I tried to call this tool as follows, but failed:

```shell
(datasci) werner@X10DAi:~/Public/hpc/vasp/learning-by-doing/optical-absorption-spectra/sumo$ sumo-optplot -f ./vasprun.xml absorption eps_imag
Traceback (most recent call last):
  File "/home/werner/.pyenv/versions/datasci/bin/sumo-optplot", line 33, in <module>
    sys.exit(load_entry_point('sumo', 'console_scripts', 'sumo-optplot')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/werner/Public/repo/github.com/SMTG-UCL/sumo.git/sumo/cli/optplot.py", line 455, in main
    optplot(
  File "/home/werner/Public/repo/github.com/SMTG-UCL/sumo.git/sumo/cli/optplot.py", line 166, in optplot
    vr = Vasprun(filename)
         ^^^^^^^^^^^^^^^^^
  File "/home/werner/Public/hpc/tools/materialsproject/pymatgen.git/pymatgen/io/vasp/outputs.py", line 363, in __init__
    with zopen(filename, "rt") as f:
         ^^^^^^^^^^^^^^^^^^^^^
  File "/home/werner/.pyenv/versions/datasci/lib/python3.11/site-packages/monty/io.py", line 45, in zopen
    return open(filename, *args, **kwargs)  # pylint: disable=R1732
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'absorption'
```
Any tips will be helpful.

Regards,
Zhao

**Comment by ajjackson** [comment]
When calling as `sumo-optplot -f ./vasprun.xml absorption eps_imag` there is some ambiguity because `-f` can take multiple files. To avoid this ambiguity, either:
- use a keyword argument that _doesn't_ take a variable number of inputs before the positional argument
  - e.g. `sumo-optplot -f ./vasprun.xml -c vasp absorption eps_imag`
- use the positional argument(s) before any keywords
  - e.g. `sumo-optplot absorption eps_imag -f ./vasprun.xml`

**Comment by hongyi-zhao** [comment]
- This way works:

```
$ sumo-optplot absorption loss eps_real eps_imag n_real n_imag -f ./vasprun.xml
```
As shown below:

![image](https://github.com/SMTG-UCL/sumo/assets/11155854/4441be45-08d8-48c6-826b-8d00829b1d15)

- This way doesn't work:
```
$ sumo-optplot -f ./vasprun.xml -c vasp absorption loss eps_real eps_imag n_real n_imag
```
As shown below:

![image](https://github.com/SMTG-UCL/sumo/assets/11155854/04206821-a275-4d0d-b406-2b30f7a2e54c)

Additional questions:

1. As you can see, in the multiple subplots generated by multiple Positional Arguments, the font size is very unreasonable, how to solve this problem automatically?
2. How do I have sumo automatically set `--xmax` and `--ymax` to generate a plot containing all value ranges of variables?

**Comment by ajjackson** [comment]
Sumo has a default figure size that is set by style sheets and not influenced by the number of subplots. This is a deliberate choice so that stylesheets can be used to get consistent plot sizes for publications etc. The size can be tweaked at a given command-line call with the `--height` and `--width` options. If producing many subplots, I would recommend to set a large `--height`.

> How can I let sumo automatically set --xmax and --ymax to generate a plot containing all value ranges of variables?

I don't understand this question. By default Sumo chooses a reasonable `--xmax` and `--ymax` for the given data. In optical absorption plots we are usually more interested in the scale up to 1e5 that gives a realistic sense of the transition from "transparent" to "opaque" materials, so this is the default; for the dielectric function plots the data range is shown.

The range can be tweaked manually with `--ymax`, which allows multiple arguments to be passed and "auto" can be used to keep automatic scaling on some of the plots.

There is not currently a way to scale absorption plots to automatically follow the full data range. I suppose one could look for it in the .dat file and replot, using this for `--ymax`?

**Comment by hongyi-zhao** [comment]
I then tried the following command:
```
(datasci) werner@X10DAi:~/Public/hpc/vasp/learning-by-doing/optical-absorption-spectra/sumo$ sumo-optplot absorption loss eps_real eps_imag n_real n_imag -f ./vasprun.xml --height 10 --xmax 20
```
And obtained the following:

![image](https://github.com/SMTG-UCL/sumo/assets/11155854/3d350d3b-8e34-46f4-a280-c130221abd45)

Now, I wonder how to adjust the scale of the x-axis?

**Comment by ajjackson** [comment]
Right. I think this may be a restriction in `argparse`, which is the (standard) library we use to handle command-line arguments. I guess you need to use the first method, then. I don't think this is a Sumo-specific issue? If there is somewhere we documented such a command, of course it should be corrected.

It looks like `--xmax` is working correctly to me, you set it to 20 and the gap from 16 to the end of the line is about half the distance from 0 to 8.

**Comment by hongyi-zhao** [comment]
> It looks like `--xmax` is working correctly to me, you set it to 20 and the gap from 16 to the end of the line is about half the distance from 0 to 8.

This is not my focus. I mean, how do I set a smaller scale, such as drawing a scale mark on the x-axis every 4 units.

**Comment by ajjackson** [comment]
I don't think it is possible to change the "major" ticker which places the numbers from the command line, but we can enable some extra marks from the "minor" ticker.

In the base stylesheet "xtick.minor.size" is set to zero. We can override that by creating an extra stylesheet. e.g. create a file "moreticks.mplstyle" and with the line
```
xtick.minor.size : 2
```

then run `sumo-optplot --style moreticks.mplstyle` and this style is added to the default to give something like
![absorption](https://github.com/SMTG-UCL/sumo/assets/2511383/ab5ba323-34a3-4cef-82b4-6ce630f1130a)

**Comment by hongyi-zhao** [comment]
However, I still don't understand how this option interacts with `--xmax` as in the following example:

```
$ cat moreticks.mplstyle 
xtick.minor.size : 10
$ sumo-optplot --style moreticks.mplstyle --xmax 10
```

The result is as follows:

![image](https://github.com/SMTG-UCL/sumo/assets/11155854/fa36de05-4f61-4400-bf6f-d85e416d28f5)

**Comment by ajjackson** [comment]
`--xmax` determines the x range shown in the plot.

Here the ticks look strange because you have set xtick.minor.size to be larger than xtick.major.size.

I don't know how matplotlib decides how many minor ticks to place or where to place the numbers. This is quite complicated and not determined by the Sumo code directly.

**Comment by ajjackson** [comment]
I think it is this: https://github.com/matplotlib/matplotlib/blob/v3.7.2/lib/matplotlib/ticker.py#L2883-L2900

So: it prefers to use values that are multiples of 1, 2, 2.5, 5 or 10, up to a maximum of 9 ticks on the axis, or a smaller number obtained by this function https://github.com/matplotlib/matplotlib/blob/d5210e4a87665581205f5147703dbd229b44cf66/lib/matplotlib/axis.py#L2474

**Comment by hongyi-zhao** [comment]
Below are some examples which using the above mentioned feature:

```python
### exampl 1
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker

# Create a simple plot
fig, ax = plt.subplots()
ax.plot([1, 2, 3, 4], [10, 20, 15, 25])

# Use AutoLocator to dynamically determine tick positions
ax.xaxis.set_major_locator(ticker.AutoLocator())

plt.show()

### exampl 2
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker

# Create a simple plot
fig, ax = plt.subplots()
ax.plot([1, 2, 3, 4], [10, 20, 15, 25])

# Customize AutoLocator with a maximum of 6 ticks and specific steps
custom_locator = ticker.AutoLocator()
custom_locator.nbins = 6
custom_locator.steps = [1, 2, 3, 4]

ax.xaxis.set_major_locator(custom_locator)

plt.show()

### exampl 3
import matplotlib.pyplot as plt

# Create a simple plot
fig, ax = plt.subplots()
ax.plot([1, 2, 3, 4], [10, 20, 15, 25])

# Adjust tick sizes
plt.rcParams['xtick.minor.size'] = 2
plt.rcParams['xtick.major.size'] = 4

plt.show()
```
But I tried in ipython as follows and still failed to display the fig directly:

```ipython
In [8]: %matplotlib inline
   ...: 
   ...: import matplotlib.pyplot as plt
   ...: import matplotlib.ticker as ticker
   ...: 
   ...: # Create a simple plot
   ...: fig, ax = plt.subplots()
   ...: ax.plot([1, 2, 3, 4], [10, 20, 15, 25])
   ...: 
   ...: # Use AutoLocator to dynamically determine tick positions
   ...: ax.xaxis.set_major_locator(ticker.AutoLocator())
   ...: 
   ...: plt.show()
Shell is already running a gui event loop for tk. Call with no arguments to disable the current loop.
<Figure size 640x480 with 1 Axes>
```
