### ISSUE TITLE
sumo-bandplot --dos crashes for more than 1 element

### ISSUE THREAD

**Issue by cnsavory** [SMTG-UCL/sumo#33]
Trying to plot combined band structure and DOS diagrams causes sumo to crash when using the default colour scheme. 

One example is the command given in the tutorials for Cs2SnI6:
`sumo-bandplot --dos ../dos/vasprun.xml.gz --ymin -4`

This appears to be because the default band structure style file only contains four colours, and the DOS, when plotted by sumo-bandplot, is drawing from these, rather than the specific DOS cycle. So, for any element after the first (if including d orbitals) it can't find sufficient colours.

**Comment by utf** [comment]
Thanks Chris, I pushed a temporary fix to the master branch and will release a new version later so that this functionality is useable.

@ajjackson Are you able to have a look at this? I thought as we are using a cycler object the colours should at least cycle and not return an error? A possible fix could be to add the dos colours from `sumo_base_style` to `sumo_bs_style` and then pass the colours minus the first for BS colours to dos plotting routines?

**Comment by ajjackson** [comment]
That is the fix I had in mind as it will also yield good/unsurprising results when other colour schemes are plugged in. An alternative to passing a colour sequence is to add a "colour_start_from" option to the dos plotter so we can tell it how many colours to skip. Passing a sequence seems a touch more consistent/less stateful.

I don't think cycling is actually desirable behaviour unless there are also linestyles involved; you *should* get an error if your plot would have indistinguishable lines. We could make that error message more informative.

**Comment by utf** [comment]
I implemented the fix I suggested above. The first 4 colours of the cycle are removed and the rest passed to the dos plotting functions.

Implemented in b88cba314cc4a93a96318117ab2fb200a542ba16.
