### ISSUE TITLE
Bandstats Effective Mass Interpretation

### ISSUE THREAD

**Issue by darnoceloc** [SMTG-UCL/sumo#40]
How does one interpret the values below from the output of the bandstats function?
I understand these values are essentially derived from the inverse of the second derivative or concavity of the conduction and valence band edges at a given k-point but which should be interpreted as the 'true' value?

 m_h: -0.187 | band 1 | [0.00, 0.00, 0.00] (1) -> [0.50, 0.50, 0.50]
  m_h: -0.288 | band 1 | [0.00, 0.00, 0.00] (1) -> [0.00, 0.00, 0.00] (1)
  m_h: -0.252 | band 1 | [0.00, 0.00, 0.00] (1) -> [0.00, 0.00, 0.00] (1)
  m_h: -0.961 | band 2 | [0.00, 0.00, 0.00] (1) -> [0.50, 0.50, 0.50]
  m_h: -0.494 | band 2 | [0.00, 0.00, 0.00] (1) -> [0.00, 0.00, 0.00] (1)
  m_h: -0.401 | band 2 | [0.00, 0.00, 0.00] (1) -> [0.00, 0.00, 0.00] (1)
  m_h: -0.961 | band 3 | [0.00, 0.00, 0.00] (1) -> [0.50, 0.50, 0.50]
  m_h: -0.494 | band 3 | [0.00, 0.00, 0.00] (1) -> [0.00, 0.00, 0.00] (1)
  m_h: -2.150 | band 3 | [0.00, 0.00, 0.00] (1) -> [0.00, 0.00, 0.00] (1)

Electron effective masses:
  m_e: 0.986 | band 4 | [0.00, 0.44, 0.44] -> [0.00, 0.00, 0.00] (1)
  m_e: 1.392 | band 4 | [0.00, 0.44, 0.44] -> [0.00, 0.00, 0.00] (1)

**Comment by ajjackson** [comment]
Presumably we have several degenerate bands at the band extrema which split with different curvatures. The most relevant effective masses will be the ones making up the band edges, i.e. they have the _lowest_ curvature, so the _largest_ effective masses i.e. -0.961 (GP->[0.5,0.5,0.5]) and 1.392 ([0,0.44,0.44]->GP).

I'm not sure what to make of the GP -> GP directions, maybe @utf has an idea about those?

For a more extensive effective mass analysis toolkit you might be interested in **https://github.com/lucydot/effmass**; this can generate annotated band structure plots which makes it easier to understand which value corresponds to which point in the band structure.

**Comment by utf** [comment]
It looks like the band path was generated by hand, rather than along the high-symmetry k-point paths. Please consider using `sumo-kgen` to generate the k-points along the high-symmetry path.

To answer your question: there is no "true" effective mass. Different bands have different curvature and therefore different effective masses. The electronic structure may also be anisotropic so the effective masses will depend the direction you are traveling. Furthermore (and this is not implemented in sumo), the actual effective mass depends on the degree of doping.

For more information I would read this excellent summary on different effective mass methods.

https://arxiv.org/abs/1811.02281

**Comment by darnoceloc** [comment]
So the effective mass being calculated by sumo here is the conventional curvature effective mass correct?

**Comment by utf** [comment]
The default is to give the parabolic effective but the non-parabolic (Kane) effective mass is also available using the `--nonparabolic` option.

For more details see: https://sumo.readthedocs.io/en/latest/sumo-bandstats.html

**Comment by darnoceloc** [comment]
I assume there are no current tools with the capability of calculating the density of states effective mass correct?
