### ISSUE TITLE
Default Colors for Elements/Orbitals

### ISSUE THREAD

**Issue by shyamd** [SMTG-UCL/sumo#8]
It would be really nice if there was a default color scheme for all elements, or could auto generate something based on the total number of elements/orbitals. Right now, I'm just hard-coding in color brewer color sets for X number of elements.

**Comment by ajjackson** [comment]
I suspect it is impossible to develop a colour scheme for all elements which allows the contributions to be easily distinguished in all compounds.

The current scheme gives reasonable contrast in my experience; can you show an example where the default behavior is particularly poor?

When you say "hard-coding" you are using a .conf file, right? I would encourage users to go with .conf files if they have opinions about colour choice. (As long as we nake sure the defaults are also decent!)

I am interested in this issue as I would like to imrove the colour-blindness accessibility; but it is difficult at this point to imagine what a colour-blind-safe quaternary PDOS would look like. Adding markers to the lines could be very effective, but also could become very cluttered.

**Comment by utf** [comment]
@shyamd 

Thanks for this comment, generating a custom scheme based on the total number of orbits would be nice.

Currently, if the orbital is not found in `orbital_colours.conf`, we choose a colour from this list of 22 colours of maximum contast: http://www.iscc.org/pdf/PC54_1724_001.pdf

**Comment by shyamd** [comment]
Also, it might be a good idea to change the Energy Label to something like E-E_f (eV) when zero'ing to the Fermi level.

**Comment by ajjackson** [comment]
The current colour palette is a sequence of 23 colours. If you think the palette needs to be improved, please be more specific about how it is failing so that we can consider our options; examples would be helpful. In my opinion this kind of line plot becomes difficult to interpret when there are more than four lines, so while there is room for improvement I would like to look further than merely tweaking colours.

I can reproduce the regeneration issue and see how that would be annoying. It is a result of the way the colour sequence is implemented as a `cycle` generator which is created at import time. This was actually done deliberately as it means that when dosplotters are called on a series of subplots the colours will be different for each. We could have an optional argument which chooses to use a fresh colour cycle or not; I have no strong preference as to which should be the default behaviour. @utf ?

I have moved the energy label discussion to a new Issue.

**Comment by shyamd** [comment]
It might be a good idea to move the color cycle into the DOS Plotter object and have subplots grab it to enumerate forward. This will ensure consistency. I should be able to run plot over and over again and get the same plot.

**Comment by shyamd** [comment]
Yeah that would be a good compromise.

**Comment by utf** [comment]
This has been addressed in #10.
