### ISSUE TITLE
Simple question about --style

### ISSUE THREAD

**Issue by Nokimann** [SMTG-UCL/sumo#97]
When we use sumo's command-line tools with `--style`, it can read files or sometimes adjust via one argument, for example, `dark_background`

I wonder how the `--style` can read given a pair of key and value set such as `font.size:10` in the command-line. Is it possible? No info. in [Iink](https://sumo.readthedocs.io/en/latest/customising-plots.html) I don't want to write `custom.mplstyle` file if possible.

**Comment by ajjackson** [comment]
I'm not convinced that
`sumo-bandplot -many -other -bandplot -args --style lines.linewidth:3 axes.labelsize:20`
is a much better user experience than
```
vi mystyle
sumo-bandplot -many -other -bandplot -args --style mystyle
```
but if you really want a one-liner there is
```
printf "lines.linewidth: 3 \naxes.labelsize: 20" > mystyle && sumo-bandplot -many -other -bandplot -args --style mystyle
```
This could be made cleaner with a shell function in your bashrc; something like

```
styled-sumo-bandplot()
{
    printf "${1//;/\\n}" > tmp.mplstyle
    shift
    sumo-bandplot --style tmp.mplstyle "$@"
    rm tmp.mplstyle
}
```
Which would then be used as
```
styled-sumo-bandplot 'lines.linewidth: 3; axes.labelsize: 20' -many -other -bandplot -args
```

To me the "hard part" of writing an mplstyle file is looking up the names of the parameters; writing the file takes seconds and is less error-prone than putting them in at the command-line. If there is a lot of demand for this one-line convenience I suppose we can add it, otherwise I would prefer not to have to maintain it.

**Comment by utf** [comment]
This might be achievable by using `type=json.loads` in argparse. Would the following syntax be useful?

```bash
sumo-bandplot -many -other -bandplot -args --style '{"lines.linewidth": 3, "axes.labelsize": 20}'
```

**Comment by Nokimann** [comment]
Yes, it works. So there are no choices to do that without changing *plot.py script. Then, it works with `type=eval` too.

@utf

**Comment by ajjackson** [comment]
`eval` is bad practice. It's not inconceivable that somebody might provide "sumo as a service" and then this would allow people to inject arbitrary code. `json.loads` would be ok from a technical standpoint. But we'd need extra logic to determine if the user passed a filename, built-in style, a valid JSON dict to update rcParams, or a something invalid.

**Comment by ajjackson** [comment]
I had a poke around with this. `json.loads` raises a `JSONDecodeError` if the input isn't valid JSON (e.g. an unquoted string...). We don't want to be raising errors in the argment parser, but we could read a string and _then_ try `json.loads`. If we catch a *JSONDecodeError*, then use it as a style name, if it turns into a json dict then we can somehow keep it around for styling.

That last step seems messy, because styling currently works by cascading matplotlib style sheets. So this user input needs to be applied *after* the style, which means the information needs to be made available to our styling decorator. Also, as this _replaces_ the style input, so you can't apply this _on top of_ a custom style. That seems counter-productive if we'd prefer people to use style files. I guess then we should allow multiple strings arguments to `--style`, the _first_ of which is tested for JSON-ness.

So. We _can_ make this work, at the cost of managing another level of styling data/complexity. Is it worth it, or are people happy with the shell function above? We could put that in the documentation somewhere if so.

**Comment by ajjackson** [comment]
Closing for now, but I don't mind re-opening for further discussion.
