### ISSUE TITLE
Use of CASTEP commands

### ISSUE THREAD

**Issue by sajidurehman** [SMTG-UCL/sumo#99]
Hi Adam,
             is it nessarry to first install CASTEP then use CASTEP commands? i tried to execute 
sumo-kgen --code castep -p Si2.cell command  but got following error.

Traceback (most recent call last):
  File "/home/max/.local/bin/sumo-kgen", line 8, in <module>
    sys.exit(main())
  File "/home/max/.local/lib/python3.6/site-packages/sumo/cli/kgen.py", line 271, in main
    cart_coords=args.cartesian, kpt_list=kpoints, labels=labels)
  File "/home/max/.local/lib/python3.6/site-packages/sumo/cli/kgen.py", line 122, in kgen
    raise ValueError('Code "{0}" not recognized.'.format(code))
ValueError: Code "castep" not recognized.

Looking forward to hear you.

**Comment by ajjackson** [comment]
Sumo should work on a machine without CASTEP installed; it just deals with the text files currently. This error message suggests that you are using a version of Sumo that does not have the (recently added) CASTEP features.

We have not yet pushed a release version to PyPI with the CASTEP features yet, so you would need to do a developer installation from the Github version. I could push out a point release with these features, but actually we'd really appreciate some feedback on how it works for you if possible!

**Comment by sajidurehman** [comment]
Hi Adam,
    Thank you for reply. Now sumo works fine with CASTEP text files. I have few queries regarding the use of sumo with CASTEP interafce.

1) is sumo-kgen supports generating k-points along custom k-point paths for CASTEP? i want to generate k-points for 2D materials e.g M-K-G-M. 
2)Similarly, for phonon band structure calculations.
3)When will Projected band structure and PDOS features available for CASTEP interface?

Looking forward to hear you again

**Comment by ajjackson** [comment]
Yes, all the other options to `kgen` should work as documented. Please report if they do not.

Unfortunately CASTEP does not expose orbital projections in a plain-text format. I am reluctant to do the difficult work of writing and maintaining a binary parser for CASTEP just for Sumo. The other options are:

- A sumo interface is developed that uses _optados_, either as part of the CASTEP tools or as its own "code". This is feasible but quite a different workflow from other codes and may not fit well in Sumo. Even then it is not clear how to get _all_ the orbitals individually, which is what Sumo generally wants as input.
- We modify CASTEP to write out plain text DOS outputs. This is unlikely to be supported by the core CASTEP team at this moment. We could write a patch, but those are not fun to distribute or maintain.
- A CASTEP binary parser is developed and maintained for use over many projects (e.g. Sumo, ASE, Pymatgen, Euphonic, ...). This looks like a realistic possibility because my colleague @stur86 has already done a lot of the work as part of https://github.com/CCP-NC/pynics. While in many ways it is the best possible outcome, it has some boring dependencies on availability/resources/politics. In my view, we should not pursue other options before this is explored further. But I cannot give a time estimate at this point.

**Comment by sajidurehman** [comment]
Hi Adam,
           Thank you for a detailed reply. 
1) Yes, all the other options to kgen should work as documented. Please report if they do not.
I have tried other options of kgen for CASTEP interface but I am facing an error. I have tried the commands in following two ways as an example
sumo-kgen --kpoints --code castep -p "0 0 0, 0.5 0.5 0.5" Si2.cell
sumo-kgen --code castep -p --kpoints "0 0 0, 0.5 0.5 0.5" Si2.cell

**Error message** 
usage: sumo-kgen [-h] [-p P] [-c CODE] [-d D] [-s N] [-f] [-y]
                 [--symprec SYMPREC] [--spg SPG] [--density DENSITY]
                 [--seekpath] [--pymatgen] [--cartesian] [--kpoints KPOINTS]
                 [--labels LABELS] [--phonon]
sumo-kgen: error: argument --kpoints: expected one argument

If sumo interface is developed that uses optados, then may be there is a way. Please have a look to the following link 

https://docs.matador.science/en/latest/tutorials/run3_spectral.html#example-2-4-using-optados-for-post-processing-projected-dos-and-bandstructures

This code (madator) also uses optados, and provided projected band structure and DOS option. But not simple and easy to use like sumo. I am using sumo for vasp. So, i also wanted to use for CASTEP interface. 

Looking forward to your kind response

**Comment by ajjackson** [comment]
The structure file should follow the argument `-p`; you have positioned it as an additional argument to `--kpoints`. Try:

```
sumo-kgen --code castep --kpoints "0 0 0, 0.5 0.5 0.5" -p Si2.cell
```

**Comment by sajidurehman** [comment]
Hi Adam,
          thank you for the right command. Now its working fine. 

Yes, may be you are right. But we (CASTEP users) anxiously waiting for projected Band Structure and DOS option in sumo.  Thank you for this exciting code (sumo). Looking forward to new exciting features for CASTEP interface.

**Comment by ajjackson** [comment]
Ok.

I see I didn't directly answer your question about phonon band structures. A `--phonon` option was added to *kgen* so that when `--code=castep` it will write a phonon q-point path instead of an electronic k-point path. The resulting `.phonon` file should be loadable with `sumo-phonon-bandplot`; have you seen the tutorial at https://github.com/ajjackson/castep-sumo-tutorial/blob/master/castep-sumo.org ?

I will close this Issue now, but thank you for your feedback re: orbital projections. We will keep in mind that this is a desirable feature.
